### ISSUE TITLE
CSS Parser for Terms of Service not parsing all CSS styles

### ISSUE THREAD

**Issue by paulvancoller-adeptadvisory** [GrindrodBank/A3S#130]
**Describe the bug**
When a complex CSS file is loaded on the terms of service screen, only certain style tags are applied to the terms <div> section. 

**To Reproduce**
1. Link a new Terms of Service entry with a complex CSS file to a team of a user that you will log in with.
2. Log in to A3S with that user using the authorization code flow (via a browser window).
3. Check the source code of the rendered page, and notice that only some of the CSS styles have been applied.

**Expected behavior**
All CSS styles need to be sanitized and applied.

**Comment by gm7** [comment]
This has been addressed in https://github.com/GrindrodBank/A3S/pull/132
