### ISSUE TITLE
RefreshTokens do not get refreshed when a fresh access token is requested

### ISSUE THREAD

**Issue by paulvancoller** [GrindrodBank/A3S#145]
**Is your feature request related to a problem? Please describe.**
RefreshTokens do not get refreshed when a fresh access token is requested. Once a refresh token has expired, there is no way of getting a new access token from the token endpoint without re-authenticating.

**Describe the solution you'd like**
Please send a fresh refresh token during access token refreshes.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by VictorSzewczenko** [comment]
This has been resolved.
