### ISSUE TITLE
Base64 encoded images not allowed on terms of sevice page

### ISSUE THREAD

**Issue by paulvancoller** [GrindrodBank/A3S#148]
**Is your feature request related to a problem? Please describe.**
Currently, base64 encoded images are not allowed on the terms of service screen. 

**Describe the solution you'd like**
Please allow base64 encoded images on the term of service page. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by melissapalmer** [comment]
This is fixed with PR #149
